node:
  image: tomcat:8.0.28-jre8
  volumes:
    - ./build/distributions/war:/usr/local/tomcat/webapps:rw
proxy:
  image: tutum/haproxy
  links:
    - node
  ports:
    - "8080:80"
  environment:
    - BALANCE=roundrobin